version: 2
registries:
  github-registry:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.JOB_TOKEN}}
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    registries:
      - github-registry
    schedule:
      interval: daily
    commit-message:
      prefix: "Dependabot-alert"
      include: scope
    allow:
        - dependency-name: "Djackk/*"
          dependency-type: "direct"