name: Caller Workflow

on:
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Environment'
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
jobs:
  setup-env:
    uses: Djackk/shared_workflows/.github/workflows/called_workflow.yaml@v1.0.0
    with:
      Environment: ${{github.event.inputs.Environment}}
    secrets:
      JOB_TOKEN: ${{ secrets.JOB_TOKEN }}